### ISSUE TITLE
Дата рождения и пол не передаются в Конвид.

### ISSUE THREAD

**Issue by victorslate** [Convead/wordpress_convead#2]
В базе есть значения строк date_of_birth и gender, и в плагине Convead Woocommerce судя по коду должна быть передача этих данных у Конвид, но она не происходит.

В WP оба поля подключены следующим образом:
`add_filter('user_contactmethods', 'my_user_contactmethods');

function my_user_contactmethods($user_contactmethods){
  $user_contactmethods['date_of_birth'] = 'Дата рождения';
  $user_contactmethods['gender'] = 'Пол';

  return $user_contactmethods;
}`

**Comment by rostber** [comment]
Передача не происходит потому что среди стандартных данных посетителей нет поля "День рождения", "Пол", в версии 4.2.x
В коде есть заготовка под передачу данных. Если в новых версиях Вордпрес появятся эти поля, то мы их добавим в функционал.

**Comment by victorslate** [comment]
А не подскажите, как к кастомным полям обратиться?
Пробовал дописать [сюда](https://github.com/Convead/wordpress_convead/blob/master/includes/convead.class.php#L475-L476)

```
if(!empty($user_data['date_of_birth'][0]))
self::$userDateofbirth = $user_data['date_of_birth'][0];
```

Не помогло...

**Comment by rostber** [comment]
Данные изменения не имеют отношения к плагину и должны делаться в вашем магазине.
